-- Doctor Login Setup SQL
-- Run this once to support dedicated doctor login with hashed passwords.

ALTER TABLE Doctor
ADD COLUMN IF NOT EXISTS password VARCHAR(255) NULL;

-- Example: set a password for a doctor account by email.
-- Replace <HASHED_PASSWORD> with a value generated by PHP password_hash().
-- UPDATE Doctor SET password = '<HASHED_PASSWORD>' WHERE email = 'doctor@example.com';
